all_with_dates <- read.csv("~/Uni/Master/WiSe 2014:15/PIP/Data Analysis/screenshots/all_with_dates.csv", stringsAsFactors=FALSE)
all_with_dates$a <- as.numeric(all_with_dates$a)
x <- data.frame(date=all_with_dates$xdate, value=all_with_dates$x)
y <- data.frame(date=all_with_dates$ydate, value=all_with_dates$y)
z <- data.frame(date=all_with_dates$zdate, value=all_with_dates$z)
a <- data.frame(date=all_with_dates$adate, value=all_with_dates$a)
rpm <- data.frame(date=all_with_dates$rpmfile, value=all_with_dates$rpm)
all <- merge(a, z, by="date", all=T)
colnames(all) <- c("date", "a", "z")
all <- merge(all, y, by="date", all=T)
colnames(all) <- c("date", "a", "z", "y")
all <- merge(all, x, by="date", all=T)
colnames(all) <- c("date", "a", "z", "y", "x")
all <- merge(all, rpm, by="date", all=T)
colnames(all) <- c("date", "a", "z", "y", "x", "rpm")
screenshots$hour <- as.numeric(strftime(screenshots$timestamp, format="%H"))
write.csv(all, "screenshots.csv", row.names=F)
